# This workflow will run tests for a Lua project
# For more information see: https://github.com/marketplace/actions/install-lua-luajit

name: Lua

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v3

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.4.4"

    - name: test
      run: |
        LUA_PATH="$PWD/src/shared/?.lua;$PWD/luaunit/?.lua" lua ./test/FilterAndSumDirectorySizesTests.lua -v
