# This workflow will run tests for a Lua project
# For more information see: https://github.com/marketplace/actions/install-lua-luajit

name: Lua

on:
  push:
    paths-ignore:
      - 'Day01CountCalories/**'
      - 'Day02RockPaperScissors/**'
      - 'Day03RucksackReorganization/**'
      - 'Day04CampCleanup/**'
      - 'Day05SupplyStacks/**'
      - 'Day06TuningTrouble/**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v3

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.4.4"

    - name: Setup git submodules
      run: |
        git submodule init
        git submodule update

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true

    - name: Test
      run: |
        LUA_PATH="$PWD/Day07NoSpaceLeftOnDevice/src/shared/?.lua;$PWD/Day07NoSpaceLeftOnDevice/test/?.lua;$PWD/Day07NoSpaceLeftOnDevice/luaunit/?.lua" lua ./Day07NoSpaceLeftOnDevice/test/TestSuite.lua -v
